# Generated by Django 4.2.7 on 2026-06-22 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('plan_type', models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('standard', 'Standard'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('lifetime', 'Lifetime')], default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trial_days', models.PositiveSmallIntegerField(default=14)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('max_products', models.PositiveIntegerField(default=100)),
                ('max_branches', models.PositiveSmallIntegerField(default=1)),
                ('max_staff', models.PositiveSmallIntegerField(default=3)),
                ('max_monthly_orders', models.PositiveIntegerField(default=500)),
                ('has_whatsapp', models.BooleanField(default=False)),
                ('has_loyalty', models.BooleanField(default=False)),
                ('has_crm', models.BooleanField(default=False)),
                ('has_marketing', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_white_label', models.BooleanField(default=False)),
                ('has_custom_domain', models.BooleanField(default=False)),
                ('has_advanced_reports', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'db_table': 'ch_subscription_plans',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('business_type', models.CharField(choices=[('single_store', 'Single Store'), ('multi_branch', 'Multi Branch'), ('multi_partner', 'Multi Partner'), ('franchise', 'Franchise'), ('online_only', 'Online Store'), ('whatsapp_store', 'WhatsApp Store'), ('wholesale', 'Wholesale')], default='single_store', max_length=30)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=300)),
                ('address_line2', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='vendors/banners/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='vendors/favicons/')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('checkout_workflow', models.CharField(choices=[('online_payment', 'Online Payment'), ('approval_payment', 'Approval then Payment'), ('whatsapp_enquiry', 'WhatsApp Enquiry'), ('cod_only', 'Cash on Delivery Only')], default='online_payment', max_length=30)),
                ('custom_domain', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('custom_css', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'ch_vendors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('renewal_reminder_sent', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_subscriptions', to='tenants.subscriptionplan')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Subscription',
                'db_table': 'ch_vendor_subscriptions',
                'ordering': ['-start_date'],
            },
        ),
    ]
