# Generated by Django 4.2.7 on 2026-07-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_vendor_razorpay_key_id_vendor_razorpay_key_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='has_custom_domain',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='custom_domain',
        ),
    ]
