# Generated by Django 4.2.7 on 2026-07-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_subscriptionplan_has_custom_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='If enabled, product stock is tracked, preventing overselling.'),
        ),
    ]
