# Generated by Django 4.2.7 on 2026-07-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_vendor_track_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. USD, EUR', max_length=5)),
                ('symbol', models.CharField(help_text='e.g. $, €', max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate relative to base currency', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_currencies', to='tenants.vendor')),
            ],
            options={
                'verbose_name': 'Supported Currency',
                'db_table': 'ch_vendor_supported_currencies',
                'ordering': ['code'],
                'unique_together': {('vendor', 'code')},
            },
        ),
    ]
