# Generated by Django 4.2.7 on 2026-07-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_supportedcurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_host_user', models.CharField(blank=True, max_length=255)),
                ('email_host_password', models.CharField(blank=True, max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
                ('welcome_discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Amount')], default='percentage', max_length=20)),
                ('welcome_discount_value', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='tenants.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Email Settings',
                'verbose_name_plural': 'Vendor Email Settings',
                'db_table': 'ch_vendor_email_settings',
            },
        ),
    ]
