# Generated by Django 4.2.7 on 2026-07-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_vendoremailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoremailsettings',
            name='popup_image',
            field=models.ImageField(blank=True, help_text='Image to display on the newsletter popup', null=True, upload_to='vendors/popups/'),
        ),
    ]
