# Generated by Django 4.2.7 on 2026-07-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_vendoremailsettings_popup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='top_announcement_text',
            field=models.CharField(blank=True, help_text='Text to display in the black top bar (e.g. Store Wide Summer Sale). Leave blank to hide.', max_length=200, null=True),
        ),
    ]
