# Generated by Django 4.2.7 on 2026-07-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_vendor_top_announcement_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vendor',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='checkout_workflow',
            field=models.CharField(choices=[('online_payment', 'Online Payment (Razorpay)'), ('online_payment_stripe', 'Online Payment (Stripe)'), ('approval_payment', 'Approval then Payment'), ('whatsapp_enquiry', 'WhatsApp Enquiry'), ('cod_only', 'Cash on Delivery Only')], default='online_payment', max_length=30),
        ),
    ]
