# Generated by Django 4.2.7 on 2026-07-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_vendor_stripe_public_key_vendor_stripe_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
