# Generated by Django 4.2.7 on 2026-07-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_vendor_stripe_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_catalog_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_inventory_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_order_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_organization_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_store_settings',
            field=models.BooleanField(default=True),
        ),
    ]
