# Generated by Django 4.2.7 on 2026-07-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_subscriptionplan_has_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='active_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vendors', to='tenants.subscriptionplan'),
        ),
    ]
