# Generated by Django 4.2.7 on 2026-07-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_vendor_active_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_otp_login',
            field=models.BooleanField(default=False),
        ),
    ]
