# Generated by Django 4.2.7 on 2026-07-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_subscriptionplan_has_otp_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
    ]
