# Generated by Django 4.2.7 on 2026-07-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_vendor_tiktok_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gcc_shipping_charge',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Shipping charge for GCC countries (UAE, Saudi Arabia, Qatar, Oman, Kuwait, Bahrain)', max_digits=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='non_gcc_shipping_charge',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Shipping charge for non-GCC countries', max_digits=10),
        ),
    ]
