# Generated by Django 4.2.7 on 2026-06-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyledger',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
