# Generated by Django 4.2.7 on 2026-07-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_vendoremailsettings'),
        ('crm', '0002_loyaltyledger_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.coupon')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscribers', to='tenants.vendor')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'db_table': 'ch_newsletter_subscribers',
                'unique_together': {('vendor', 'email')},
            },
        ),
    ]
