# Generated by Django 4.2.7 on 2026-07-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_sections', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Info Section',
                'verbose_name_plural': 'Product Info Sections',
                'db_table': 'ch_product_info_sections',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
