# Generated by Django 4.2.7 on 2026-07-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productinfosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
