# Generated by Django 4.2.7 on 2026-07-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_attributes_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfosection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_info/'),
        ),
        migrations.AlterField(
            model_name='productinfosection',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
