# Generated by Django 4.2.7 on 2026-07-15 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0007_order_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
