# Generated by Django 4.2.7 on 2026-07-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_subscriptionplan_has_otp_login'),
        ('storefront', '0008_alter_order_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g. MAISON ATELIER — NEW COLLECTION', max_length=100)),
                ('title', models.CharField(help_text='Main heading. You can use HTML like <br> and <span>.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, default='Explore Details', max_length=50)),
                ('button_link', models.CharField(blank=True, default='#', max_length=255)),
                ('image', models.ImageField(help_text='Recommended size: 1920x1080px (16:9 Aspect Ratio) or 2000x1200px', upload_to='carousel_images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sequence order of the slide')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_slides', to='tenants.vendor')),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'db_table': 'ch_carousel_slides',
                'ordering': ['order'],
            },
        ),
    ]
